### ISSUE TITLE
Make stageportal able to be installed using pip

### ISSUE THREAD

**Issue by elyezer** [RedHatQE/python-stageportal#1]
Layout the project directory structure and add setup.py to make python-stageportal able to be installed using pip.

Also will be nice to add it to PyPi.

Reference: http://docs.python.org/2.7/distutils/

**Comment by omaciel** [comment]
Hey @vittyvk would it be possible for you to create a setup.py so that we can install python-stageportal via pip?

``` bash
$ pip install -e git+https://github.com/RedHatQE/python-stageportal.git
```

This would be extremely helpful for us :)

Thanks in advance!
