### ISSUE TITLE
Better place to stageportal.cfg?

### ISSUE THREAD

**Issue by elyezer** [RedHatQE/python-stageportal#4]
When installing stageportal using pip I could not install it without sudo because `error: /etc/stageportal.cfg: Permission denied`. And as that file is just a sample config file:

```
[main]
api = http://api.example.com:8080/svcrest
portal = https://portal.example.com

[subman]
candlepin = https://candlepin.example.com

[rhn]
xmlrpc = https://xmlrpc.server.example.com.com/XMLRPC
```

I don't think that requiring sudo to just drop it under /etc/ is a good thing and would like to propose to discuss more about the issue.

**Comment by vittyvk** [comment]
Well, /etc/stageportal.cfg is supposed to be a global config and it's not convenient to install it with pip, I agree. 

I would suggest the following approach:
1) Exclude /etc/stageportal.cfg from setup.py and move it to rpm spec
2) Add the following logic in code: first check for global (/etc/stageportal.cfg) config and use it if it's present, than check for local (e.g. ~/.stageportal) config and use it if it's present (overrides global).

Does that sound good?

**Comment by elyezer** [comment]
That would be nice.

Also when I see a python package with setup.py I would expect that it is installable via pip and available in pypi.

Btw, stageportal relies on  rhsm that relies on rpm and are not available on pypi. The python rpm is even worst because I was not able to find it on github, or grab the git url to install via pip using git.

But I think these are nice tools and would be even better to have them available in pypi.

**Comment by elyezer** [comment]
No relevant anymore.
